### ISSUE TITLE
Can't add the SPM package

### ISSUE THREAD

**Issue by budidino** [surveysparrow/surveysparrow-ios-sdk#20]
I'm trying to switch from Cocoapods to SPM but I get this issue when trying to add the package:

![Screenshot 2024-10-01 at 15 36 44](https://github.com/user-attachments/assets/acdf1d9e-3d21-4ad4-9925-fe030280461c)

    unexpectedly did not find the new dependency in the package graph:
    sourceControl(
        identity: surveysparrow-ios-sdk,
        location: SwiftPM.SPMPackageDependency.SourceControlLocation.remote(
            SwiftPM.SPMSourceControlURL(sourceControlURL: https://github.com/surveysparrow/surveysparrow-ios-sdk.git)
        ),
        requirement: 1.2.0 - Next Major
    )

I tried resolving package caches, restarting Xcode, cleaning derived data, ...

**Comment by Gokulkrishna-Raju** [comment]
> @budidino, Thanks to reaching us.


This issue can't be reproduced from our side, and we also have active users importing v1.2.0.

**You can also try the following:**

### 1. Remove SPM Caches
```shell
rm -rf ~/Library/Caches/org.swift.swiftpm
rm -rf ~/Library/Developer/Xcode/DerivedData/*
rm -rf .build
``` 

### 2. Adjust the Version Specification
```
.exact("1.2.0") or .upToNextMajor(from: "1.2.0")
``` 

### 3. Check Network and Proxy Settings

- Temporarily disable any VPNs or proxies.
- Ensure that your firewall isn’t blocking GitHub.

### 4. Check Compatibility

- Ensure your environment supports the Swift tools version: 5.9.
- Ensure the Swift Package Manager (SPM) is correctly set up and integrated in your project.

## After all the checks 
- Remove the Surveysparrow iOS SDK.
- Re-add it with the correct URL and version requirement.

> **Hope this will resolve your issue**

**Comment by budidino** [comment]
It seems like some part of the proposed step 1 helped fix it. Thank you! 🚀
